/* ============================================================
   MINGO LINGUO - WORD DECK
   Language: Romanian (ro)  |  702 words  |  ASCII (diacritics stripped)
   ------------------------------------------------------------
   ADD WORDS: append objects to the words array.
     key  - unique stable id (use foreign word; never rename)
     fw   - foreign word     en - English
     pos  - part of speech   g  - gender (m/f/n) for nouns
     note - optional hint shown small under the answer
   Loaded by index.html as window.MINGO_DECK.
   New language: copy file, change lang/langName/voice, swap
   the <script src> tag in the HTML.
   ============================================================ */

var MINGO_DECK = {
  lang: "ro",
  langName: "Romanian",
  voice: "ro-RO",
  words: [
    { key: "si", fw: "si", en: "and", pos: "conj" },
    { key: "a fi", fw: "a fi", en: "to be", pos: "v" },
    { key: "a avea", fw: "a avea", en: "to have", pos: "v" },
    { key: "eu", fw: "eu", en: "I", pos: "pron" },
    { key: "tu", fw: "tu", en: "you (sing.)", pos: "pron" },
    { key: "el", fw: "el", en: "he", pos: "pron" },
    { key: "ea", fw: "ea", en: "she", pos: "pron" },
    { key: "noi", fw: "noi", en: "we", pos: "pron" },
    { key: "voi", fw: "voi", en: "you (pl.)", pos: "pron" },
    { key: "ei", fw: "ei", en: "they (m.)", pos: "pron" },
    { key: "ele", fw: "ele", en: "they (f.)", pos: "pron" },
    { key: "nu", fw: "nu", en: "no, not", pos: "adv" },
    { key: "da", fw: "da", en: "yes", pos: "adv" },
    { key: "ce", fw: "ce", en: "what", pos: "pron" },
    { key: "cine", fw: "cine", en: "who", pos: "pron" },
    { key: "unde", fw: "unde", en: "where", pos: "adv" },
    { key: "cand", fw: "cand", en: "when", pos: "adv" },
    { key: "cum", fw: "cum", en: "how", pos: "adv" },
    { key: "de ce", fw: "de ce", en: "why", pos: "adv" },
    { key: "care", fw: "care", en: "which", pos: "pron" },
    { key: "acest", fw: "acest", en: "this", pos: "adj" },
    { key: "acel", fw: "acel", en: "that", pos: "adj" },
    { key: "om", fw: "om", en: "man, person", pos: "n", g: "m" },
    { key: "femeie", fw: "femeie", en: "woman", pos: "n", g: "f" },
    { key: "copil", fw: "copil", en: "child", pos: "n", g: "m" },
    { key: "baiat", fw: "baiat", en: "boy", pos: "n", g: "m" },
    { key: "fata", fw: "fata", en: "girl", pos: "n", g: "f" },
    { key: "casa", fw: "casa", en: "house", pos: "n", g: "f" },
    { key: "apa", fw: "apa", en: "water", pos: "n", g: "f" },
    { key: "paine", fw: "paine", en: "bread", pos: "n", g: "f" },
    { key: "timp", fw: "timp", en: "time", pos: "n", g: "n" },
    { key: "zi", fw: "zi", en: "day", pos: "n", g: "f" },
    { key: "noapte", fw: "noapte", en: "night", pos: "n", g: "f" },
    { key: "an", fw: "an", en: "year", pos: "n", g: "m" },
    { key: "luna", fw: "luna", en: "month, moon", pos: "n", g: "f" },
    { key: "saptamana", fw: "saptamana", en: "week", pos: "n", g: "f" },
    { key: "ora", fw: "ora", en: "hour", pos: "n", g: "f" },
    { key: "minut", fw: "minut", en: "minute", pos: "n", g: "n" },
    { key: "mana", fw: "mana", en: "hand", pos: "n", g: "f" },
    { key: "ochi", fw: "ochi", en: "eye", pos: "n", g: "m" },
    { key: "cap", fw: "cap", en: "head", pos: "n", g: "n" },
    { key: "picior", fw: "picior", en: "foot, leg", pos: "n", g: "n" },
    { key: "inima", fw: "inima", en: "heart", pos: "n", g: "f" },
    { key: "gura", fw: "gura", en: "mouth", pos: "n", g: "f" },
    { key: "oras", fw: "oras", en: "city", pos: "n", g: "n" },
    { key: "tara", fw: "tara", en: "country", pos: "n", g: "f" },
    { key: "drum", fw: "drum", en: "road, way", pos: "n", g: "n" },
    { key: "masina", fw: "masina", en: "car", pos: "n", g: "f" },
    { key: "carte", fw: "carte", en: "book", pos: "n", g: "f" },
    { key: "prieten", fw: "prieten", en: "friend", pos: "n", g: "m" },
    { key: "mama", fw: "mama", en: "mother", pos: "n", g: "f" },
    { key: "tata", fw: "tata", en: "father", pos: "n", g: "m" },
    { key: "frate", fw: "frate", en: "brother", pos: "n", g: "m" },
    { key: "sora", fw: "sora", en: "sister", pos: "n", g: "f" },
    { key: "fiu", fw: "fiu", en: "son", pos: "n", g: "m" },
    { key: "fiica", fw: "fiica", en: "daughter", pos: "n", g: "f" },
    { key: "a face", fw: "a face", en: "to do, to make", pos: "v" },
    { key: "a merge", fw: "a merge", en: "to go", pos: "v" },
    { key: "a veni", fw: "a veni", en: "to come", pos: "v" },
    { key: "a vedea", fw: "a vedea", en: "to see", pos: "v" },
    { key: "a sti", fw: "a sti", en: "to know", pos: "v" },
    { key: "a vrea", fw: "a vrea", en: "to want", pos: "v" },
    { key: "a putea", fw: "a putea", en: "to be able", pos: "v" },
    { key: "a spune", fw: "a spune", en: "to say", pos: "v" },
    { key: "a da", fw: "a da", en: "to give", pos: "v" },
    { key: "a lua", fw: "a lua", en: "to take", pos: "v" },
    { key: "a manca", fw: "a manca", en: "to eat", pos: "v" },
    { key: "a bea", fw: "a bea", en: "to drink", pos: "v" },
    { key: "a dormi", fw: "a dormi", en: "to sleep", pos: "v" },
    { key: "a vorbi", fw: "a vorbi", en: "to speak", pos: "v" },
    { key: "a citi", fw: "a citi", en: "to read", pos: "v" },
    { key: "a scrie", fw: "a scrie", en: "to write", pos: "v" },
    { key: "a iubi", fw: "a iubi", en: "to love", pos: "v" },
    { key: "a gandi", fw: "a gandi", en: "to think", pos: "v" },
    { key: "a crede", fw: "a crede", en: "to believe", pos: "v" },
    { key: "a intelege", fw: "a intelege", en: "to understand", pos: "v" },
    { key: "a auzi", fw: "a auzi", en: "to hear", pos: "v" },
    { key: "a astepta", fw: "a astepta", en: "to wait", pos: "v" },
    { key: "a gasi", fw: "a gasi", en: "to find", pos: "v" },
    { key: "a pierde", fw: "a pierde", en: "to lose", pos: "v" },
    { key: "a castiga", fw: "a castiga", en: "to win, earn", pos: "v" },
    { key: "a cumpara", fw: "a cumpara", en: "to buy", pos: "v" },
    { key: "a vinde", fw: "a vinde", en: "to sell", pos: "v" },
    { key: "a plati", fw: "a plati", en: "to pay", pos: "v" },
    { key: "a lucra", fw: "a lucra", en: "to work", pos: "v" },
    { key: "a juca", fw: "a juca", en: "to play", pos: "v" },
    { key: "a canta", fw: "a canta", en: "to sing, play", pos: "v" },
    { key: "a deschide", fw: "a deschide", en: "to open", pos: "v" },
    { key: "a inchide", fw: "a inchide", en: "to close", pos: "v" },
    { key: "a incepe", fw: "a incepe", en: "to begin", pos: "v" },
    { key: "a termina", fw: "a termina", en: "to finish", pos: "v" },
    { key: "a ramane", fw: "a ramane", en: "to remain", pos: "v" },
    { key: "a pleca", fw: "a pleca", en: "to leave", pos: "v" },
    { key: "a sosi", fw: "a sosi", en: "to arrive", pos: "v" },
    { key: "a intra", fw: "a intra", en: "to enter", pos: "v" },
    { key: "a iesi", fw: "a iesi", en: "to exit", pos: "v" },
    { key: "a urca", fw: "a urca", en: "to climb, go up", pos: "v" },
    { key: "a cobori", fw: "a cobori", en: "to go down", pos: "v" },
    { key: "a aduce", fw: "a aduce", en: "to bring", pos: "v" },
    { key: "a duce", fw: "a duce", en: "to carry", pos: "v" },
    { key: "a pune", fw: "a pune", en: "to put", pos: "v" },
    { key: "a tine", fw: "a tine", en: "to hold", pos: "v" },
    { key: "a lasa", fw: "a lasa", en: "to let, leave", pos: "v" },
    { key: "a primi", fw: "a primi", en: "to receive", pos: "v" },
    { key: "a trimite", fw: "a trimite", en: "to send", pos: "v" },
    { key: "a arata", fw: "a arata", en: "to show", pos: "v" },
    { key: "a ajuta", fw: "a ajuta", en: "to help", pos: "v" },
    { key: "a invata", fw: "a invata", en: "to learn, teach", pos: "v" },
    { key: "a uita", fw: "a uita", en: "to forget", pos: "v" },
    { key: "a aminti", fw: "a aminti", en: "to remember", pos: "v" },
    { key: "a simti", fw: "a simti", en: "to feel", pos: "v" },
    { key: "a parea", fw: "a parea", en: "to seem", pos: "v" },
    { key: "a trebui", fw: "a trebui", en: "to must", pos: "v" },
    { key: "a incerca", fw: "a incerca", en: "to try", pos: "v" },
    { key: "a reusi", fw: "a reusi", en: "to succeed", pos: "v" },
    { key: "a schimba", fw: "a schimba", en: "to change", pos: "v" },
    { key: "a ajunge", fw: "a ajunge", en: "to reach", pos: "v" },
    { key: "a trai", fw: "a trai", en: "to live", pos: "v" },
    { key: "a muri", fw: "a muri", en: "to die", pos: "v" },
    { key: "a naste", fw: "a naste", en: "to give birth", pos: "v" },
    { key: "a creste", fw: "a creste", en: "to grow", pos: "v" },
    { key: "a cadea", fw: "a cadea", en: "to fall", pos: "v" },
    { key: "a ridica", fw: "a ridica", en: "to lift, raise", pos: "v" },
    { key: "a alerga", fw: "a alerga", en: "to run", pos: "v" },
    { key: "a sari", fw: "a sari", en: "to jump", pos: "v" },
    { key: "a inota", fw: "a inota", en: "to swim", pos: "v" },
    { key: "a zbura", fw: "a zbura", en: "to fly", pos: "v" },
    { key: "a conduce", fw: "a conduce", en: "to drive, lead", pos: "v" },
    { key: "a opri", fw: "a opri", en: "to stop", pos: "v" },
    { key: "a misca", fw: "a misca", en: "to move", pos: "v" },
    { key: "a arunca", fw: "a arunca", en: "to throw", pos: "v" },
    { key: "a prinde", fw: "a prinde", en: "to catch", pos: "v" },
    { key: "a rupe", fw: "a rupe", en: "to break, tear", pos: "v" },
    { key: "a taia", fw: "a taia", en: "to cut", pos: "v" },
    { key: "a construi", fw: "a construi", en: "to build", pos: "v" },
    { key: "a sparge", fw: "a sparge", en: "to smash", pos: "v" },
    { key: "a spala", fw: "a spala", en: "to wash", pos: "v" },
    { key: "a curata", fw: "a curata", en: "to clean", pos: "v" },
    { key: "a gati", fw: "a gati", en: "to cook", pos: "v" },
    { key: "a coace", fw: "a coace", en: "to bake", pos: "v" },
    { key: "a servi", fw: "a servi", en: "to serve", pos: "v" },
    { key: "a oferi", fw: "a oferi", en: "to offer", pos: "v" },
    { key: "a cere", fw: "a cere", en: "to ask for", pos: "v" },
    { key: "a intreba", fw: "a intreba", en: "to ask", pos: "v" },
    { key: "a raspunde", fw: "a raspunde", en: "to answer", pos: "v" },
    { key: "a chema", fw: "a chema", en: "to call", pos: "v" },
    { key: "a striga", fw: "a striga", en: "to shout", pos: "v" },
    { key: "a rade", fw: "a rade", en: "to laugh", pos: "v" },
    { key: "a plange", fw: "a plange", en: "to cry", pos: "v" },
    { key: "a zambi", fw: "a zambi", en: "to smile", pos: "v" },
    { key: "a privi", fw: "a privi", en: "to watch", pos: "v" },
    { key: "a cauta", fw: "a cauta", en: "to search", pos: "v" },
    { key: "a alege", fw: "a alege", en: "to choose", pos: "v" },
    { key: "a decide", fw: "a decide", en: "to decide", pos: "v" },
    { key: "a hotari", fw: "a hotari", en: "to decide", pos: "v" },
    { key: "a permite", fw: "a permite", en: "to allow", pos: "v" },
    { key: "a interzice", fw: "a interzice", en: "to forbid", pos: "v" },
    { key: "a promite", fw: "a promite", en: "to promise", pos: "v" },
    { key: "a refuza", fw: "a refuza", en: "to refuse", pos: "v" },
    { key: "a accepta", fw: "a accepta", en: "to accept", pos: "v" },
    { key: "a multumi", fw: "a multumi", en: "to thank", pos: "v" },
    { key: "a saruta", fw: "a saruta", en: "to kiss", pos: "v" },
    { key: "a imbratisa", fw: "a imbratisa", en: "to hug", pos: "v" },
    { key: "a lupta", fw: "a lupta", en: "to fight", pos: "v" },
    { key: "a apara", fw: "a apara", en: "to defend", pos: "v" },
    { key: "a ataca", fw: "a ataca", en: "to attack", pos: "v" },
    { key: "mare", fw: "mare", en: "big", pos: "adj" },
    { key: "mic", fw: "mic", en: "small", pos: "adj" },
    { key: "bun", fw: "bun", en: "good", pos: "adj" },
    { key: "rau", fw: "rau", en: "bad", pos: "adj" },
    { key: "nou", fw: "nou", en: "new", pos: "adj" },
    { key: "vechi", fw: "vechi", en: "old", pos: "adj" },
    { key: "tanar", fw: "tanar", en: "young", pos: "adj" },
    { key: "batran", fw: "batran", en: "old (person)", pos: "adj" },
    { key: "frumos", fw: "frumos", en: "beautiful", pos: "adj" },
    { key: "urat", fw: "urat", en: "ugly", pos: "adj" },
    { key: "lung", fw: "lung", en: "long", pos: "adj" },
    { key: "scurt", fw: "scurt", en: "short", pos: "adj" },
    { key: "inalt", fw: "inalt", en: "tall, high", pos: "adj" },
    { key: "jos", fw: "jos", en: "low, down", pos: "adj" },
    { key: "larg", fw: "larg", en: "wide", pos: "adj" },
    { key: "ingust", fw: "ingust", en: "narrow", pos: "adj" },
    { key: "gros", fw: "gros", en: "thick", pos: "adj" },
    { key: "subtire", fw: "subtire", en: "thin", pos: "adj" },
    { key: "greu", fw: "greu", en: "hard, heavy", pos: "adj" },
    { key: "usor", fw: "usor", en: "easy, light", pos: "adj" },
    { key: "cald", fw: "cald", en: "warm", pos: "adj" },
    { key: "rece", fw: "rece", en: "cold", pos: "adj" },
    { key: "fierbinte", fw: "fierbinte", en: "hot", pos: "adj" },
    { key: "uscat", fw: "uscat", en: "dry", pos: "adj" },
    { key: "ud", fw: "ud", en: "wet", pos: "adj" },
    { key: "plin", fw: "plin", en: "full", pos: "adj" },
    { key: "gol", fw: "gol", en: "empty", pos: "adj" },
    { key: "curat", fw: "curat", en: "clean", pos: "adj" },
    { key: "murdar", fw: "murdar", en: "dirty", pos: "adj" },
    { key: "bogat", fw: "bogat", en: "rich", pos: "adj" },
    { key: "sarac", fw: "sarac", en: "poor", pos: "adj" },
    { key: "scump", fw: "scump", en: "expensive, dear", pos: "adj" },
    { key: "ieftin", fw: "ieftin", en: "cheap", pos: "adj" },
    { key: "puternic", fw: "puternic", en: "strong", pos: "adj" },
    { key: "slab", fw: "slab", en: "weak, thin", pos: "adj" },
    { key: "rapid", fw: "rapid", en: "fast", pos: "adj" },
    { key: "lent", fw: "lent", en: "slow", pos: "adj" },
    { key: "intunecat", fw: "intunecat", en: "dark", pos: "adj" },
    { key: "luminos", fw: "luminos", en: "bright", pos: "adj" },
    { key: "clar", fw: "clar", en: "clear", pos: "adj" },
    { key: "adevarat", fw: "adevarat", en: "true", pos: "adj" },
    { key: "fals", fw: "fals", en: "false", pos: "adj" },
    { key: "important", fw: "important", en: "important", pos: "adj" },
    { key: "dificil", fw: "dificil", en: "difficult", pos: "adj" },
    { key: "posibil", fw: "posibil", en: "possible", pos: "adj" },
    { key: "imposibil", fw: "imposibil", en: "impossible", pos: "adj" },
    { key: "sigur", fw: "sigur", en: "sure, safe", pos: "adj" },
    { key: "periculos", fw: "periculos", en: "dangerous", pos: "adj" },
    { key: "liber", fw: "liber", en: "free", pos: "adj" },
    { key: "ocupat", fw: "ocupat", en: "busy", pos: "adj" },
    { key: "fericit", fw: "fericit", en: "happy", pos: "adj" },
    { key: "trist", fw: "trist", en: "sad", pos: "adj" },
    { key: "vesel", fw: "vesel", en: "cheerful", pos: "adj" },
    { key: "suparat", fw: "suparat", en: "upset, angry", pos: "adj" },
    { key: "obosit", fw: "obosit", en: "tired", pos: "adj" },
    { key: "bolnav", fw: "bolnav", en: "sick", pos: "adj" },
    { key: "sanatos", fw: "sanatos", en: "healthy", pos: "adj" },
    { key: "viu", fw: "viu", en: "alive", pos: "adj" },
    { key: "mort", fw: "mort", en: "dead", pos: "adj" },
    { key: "intreg", fw: "intreg", en: "whole", pos: "adj" },
    { key: "singur", fw: "singur", en: "alone", pos: "adj" },
    { key: "acelasi", fw: "acelasi", en: "same", pos: "adj" },
    { key: "diferit", fw: "diferit", en: "different", pos: "adj" },
    { key: "alb", fw: "alb", en: "white", pos: "adj" },
    { key: "negru", fw: "negru", en: "black", pos: "adj" },
    { key: "rosu", fw: "rosu", en: "red", pos: "adj" },
    { key: "verde", fw: "verde", en: "green", pos: "adj" },
    { key: "albastru", fw: "albastru", en: "blue", pos: "adj" },
    { key: "galben", fw: "galben", en: "yellow", pos: "adj" },
    { key: "maro", fw: "maro", en: "brown", pos: "adj" },
    { key: "gri", fw: "gri", en: "grey", pos: "adj" },
    { key: "roz", fw: "roz", en: "pink", pos: "adj" },
    { key: "portocaliu", fw: "portocaliu", en: "orange", pos: "adj" },
    { key: "violet", fw: "violet", en: "purple", pos: "adj" },
    { key: "aici", fw: "aici", en: "here", pos: "adv" },
    { key: "acolo", fw: "acolo", en: "there", pos: "adv" },
    { key: "acum", fw: "acum", en: "now", pos: "adv" },
    { key: "azi", fw: "azi", en: "today", pos: "adv" },
    { key: "maine", fw: "maine", en: "tomorrow", pos: "adv" },
    { key: "ieri", fw: "ieri", en: "yesterday", pos: "adv" },
    { key: "devreme", fw: "devreme", en: "early", pos: "adv" },
    { key: "tarziu", fw: "tarziu", en: "late", pos: "adv" },
    { key: "mereu", fw: "mereu", en: "always", pos: "adv" },
    { key: "niciodata", fw: "niciodata", en: "never", pos: "adv" },
    { key: "des", fw: "des", en: "often", pos: "adv" },
    { key: "rar", fw: "rar", en: "rarely", pos: "adv" },
    { key: "uneori", fw: "uneori", en: "sometimes", pos: "adv" },
    { key: "deja", fw: "deja", en: "already", pos: "adv" },
    { key: "inca", fw: "inca", en: "still, yet", pos: "adv" },
    { key: "foarte", fw: "foarte", en: "very", pos: "adv" },
    { key: "bine", fw: "bine", en: "well", pos: "adv" },
    { key: "prost", fw: "prost", en: "badly", pos: "adv" },
    { key: "repede", fw: "repede", en: "fast", pos: "adv" },
    { key: "incet", fw: "incet", en: "slowly", pos: "adv" },
    { key: "impreuna", fw: "impreuna", en: "together", pos: "adv" },
    { key: "afara", fw: "afara", en: "outside", pos: "adv" },
    { key: "inauntru", fw: "inauntru", en: "inside", pos: "adv" },
    { key: "sus", fw: "sus", en: "up", pos: "adv" },
    { key: "aproape", fw: "aproape", en: "near, almost", pos: "adv" },
    { key: "departe", fw: "departe", en: "far", pos: "adv" },
    { key: "inainte", fw: "inainte", en: "before, ahead", pos: "adv" },
    { key: "dupa", fw: "dupa", en: "after", pos: "prep" },
    { key: "inapoi", fw: "inapoi", en: "back", pos: "adv" },
    { key: "din nou", fw: "din nou", en: "again", pos: "adv" },
    { key: "doar", fw: "doar", en: "only", pos: "adv" },
    { key: "chiar", fw: "chiar", en: "even, really", pos: "adv" },
    { key: "poate", fw: "poate", en: "maybe", pos: "adv" },
    { key: "desigur", fw: "desigur", en: "of course", pos: "adv" },
    { key: "astfel", fw: "astfel", en: "thus", pos: "adv" },
    { key: "asadar", fw: "asadar", en: "therefore", pos: "adv" },
    { key: "totusi", fw: "totusi", en: "however", pos: "adv" },
    { key: "destul", fw: "destul", en: "enough", pos: "adv" },
    { key: "prea", fw: "prea", en: "too (much)", pos: "adv" },
    { key: "mai", fw: "mai", en: "more", pos: "adv" },
    { key: "cel mai", fw: "cel mai", en: "most", pos: "adv" },
    { key: "in", fw: "in", en: "in", pos: "prep" },
    { key: "pe", fw: "pe", en: "on", pos: "prep" },
    { key: "la", fw: "la", en: "at, to", pos: "prep" },
    { key: "cu", fw: "cu", en: "with", pos: "prep" },
    { key: "fara", fw: "fara", en: "without", pos: "prep" },
    { key: "pentru", fw: "pentru", en: "for", pos: "prep" },
    { key: "din", fw: "din", en: "from, of", pos: "prep" },
    { key: "de", fw: "de", en: "of, from", pos: "prep" },
    { key: "sub", fw: "sub", en: "under", pos: "prep" },
    { key: "peste", fw: "peste", en: "over", pos: "prep" },
    { key: "langa", fw: "langa", en: "next to", pos: "prep" },
    { key: "intre", fw: "intre", en: "between", pos: "prep" },
    { key: "spre", fw: "spre", en: "towards", pos: "prep" },
    { key: "pana", fw: "pana", en: "until", pos: "prep" },
    { key: "prin", fw: "prin", en: "through", pos: "prep" },
    { key: "contra", fw: "contra", en: "against", pos: "prep" },
    { key: "dar", fw: "dar", en: "but", pos: "conj" },
    { key: "sau", fw: "sau", en: "or", pos: "conj" },
    { key: "pentru ca", fw: "pentru ca", en: "because", pos: "conj" },
    { key: "daca", fw: "daca", en: "if", pos: "conj" },
    { key: "ca", fw: "ca", en: "that", pos: "conj" },
    { key: "sa", fw: "sa", en: "to (subj.)", pos: "conj" },
    { key: "desi", fw: "desi", en: "although", pos: "conj" },
    { key: "ci", fw: "ci", en: "but rather", pos: "conj" },
    { key: "nici", fw: "nici", en: "nor", pos: "conj" },
    { key: "deci", fw: "deci", en: "so", pos: "conj" },
    { key: "unu", fw: "unu", en: "one", pos: "num" },
    { key: "doi", fw: "doi", en: "two", pos: "num" },
    { key: "trei", fw: "trei", en: "three", pos: "num" },
    { key: "patru", fw: "patru", en: "four", pos: "num" },
    { key: "cinci", fw: "cinci", en: "five", pos: "num" },
    { key: "sase", fw: "sase", en: "six", pos: "num" },
    { key: "sapte", fw: "sapte", en: "seven", pos: "num" },
    { key: "opt", fw: "opt", en: "eight", pos: "num" },
    { key: "noua", fw: "noua", en: "nine", pos: "num" },
    { key: "zece", fw: "zece", en: "ten", pos: "num" },
    { key: "unsprezece", fw: "unsprezece", en: "eleven", pos: "num" },
    { key: "doisprezece", fw: "doisprezece", en: "twelve", pos: "num" },
    { key: "douazeci", fw: "douazeci", en: "twenty", pos: "num" },
    { key: "treizeci", fw: "treizeci", en: "thirty", pos: "num" },
    { key: "o suta", fw: "o suta", en: "hundred", pos: "num" },
    { key: "o mie", fw: "o mie", en: "thousand", pos: "num" },
    { key: "primul", fw: "primul", en: "first", pos: "num" },
    { key: "al doilea", fw: "al doilea", en: "second", pos: "num" },
    { key: "ultimul", fw: "ultimul", en: "last", pos: "num" },
    { key: "jumatate", fw: "jumatate", en: "half", pos: "n", g: "f" },
    { key: "bani", fw: "bani", en: "money", pos: "n", g: "m" },
    { key: "lucru", fw: "lucru", en: "thing, work", pos: "n", g: "n" },
    { key: "viata", fw: "viata", en: "life", pos: "n", g: "f" },
    { key: "moarte", fw: "moarte", en: "death", pos: "n", g: "f" },
    { key: "lume", fw: "lume", en: "world, people", pos: "n", g: "f" },
    { key: "loc", fw: "loc", en: "place", pos: "n", g: "n" },
    { key: "nume", fw: "nume", en: "name", pos: "n", g: "n" },
    { key: "cuvant", fw: "cuvant", en: "word", pos: "n", g: "n" },
    { key: "limba", fw: "limba", en: "language, tongue", pos: "n", g: "f" },
    { key: "intrebare", fw: "intrebare", en: "question", pos: "n", g: "f" },
    { key: "raspuns", fw: "raspuns", en: "answer", pos: "n", g: "n" },
    { key: "problema", fw: "problema", en: "problem", pos: "n", g: "f" },
    { key: "idee", fw: "idee", en: "idea", pos: "n", g: "f" },
    { key: "gand", fw: "gand", en: "thought", pos: "n", g: "n" },
    { key: "vis", fw: "vis", en: "dream", pos: "n", g: "n" },
    { key: "adevar", fw: "adevar", en: "truth", pos: "n", g: "n" },
    { key: "minciuna", fw: "minciuna", en: "lie", pos: "n", g: "f" },
    { key: "poveste", fw: "poveste", en: "story", pos: "n", g: "f" },
    { key: "usa", fw: "usa", en: "door", pos: "n", g: "f" },
    { key: "fereastra", fw: "fereastra", en: "window", pos: "n", g: "f" },
    { key: "masa", fw: "masa", en: "table, meal", pos: "n", g: "f" },
    { key: "scaun", fw: "scaun", en: "chair", pos: "n", g: "n" },
    { key: "pat", fw: "pat", en: "bed", pos: "n", g: "n" },
    { key: "camera", fw: "camera", en: "room", pos: "n", g: "f" },
    { key: "perete", fw: "perete", en: "wall", pos: "n", g: "m" },
    { key: "podea", fw: "podea", en: "floor", pos: "n", g: "f" },
    { key: "acoperis", fw: "acoperis", en: "roof", pos: "n", g: "n" },
    { key: "gradina", fw: "gradina", en: "garden", pos: "n", g: "f" },
    { key: "strada", fw: "strada", en: "street", pos: "n", g: "f" },
    { key: "podul", fw: "podul", en: "bridge", pos: "n", g: "n" },
    { key: "biserica", fw: "biserica", en: "church", pos: "n", g: "f" },
    { key: "scoala", fw: "scoala", en: "school", pos: "n", g: "f" },
    { key: "spital", fw: "spital", en: "hospital", pos: "n", g: "n" },
    { key: "magazin", fw: "magazin", en: "shop", pos: "n", g: "n" },
    { key: "piata", fw: "piata", en: "market, square", pos: "n", g: "f" },
    { key: "banca", fw: "banca", en: "bank, bench", pos: "n", g: "f" },
    { key: "birou", fw: "birou", en: "office, desk", pos: "n", g: "n" },
    { key: "fabrica", fw: "fabrica", en: "factory", pos: "n", g: "f" },
    { key: "foc", fw: "foc", en: "fire", pos: "n", g: "n" },
    { key: "soare", fw: "soare", en: "sun", pos: "n", g: "m" },
    { key: "stea", fw: "stea", en: "star", pos: "n", g: "f" },
    { key: "cer", fw: "cer", en: "sky", pos: "n", g: "n" },
    { key: "nor", fw: "nor", en: "cloud", pos: "n", g: "m" },
    { key: "ploaie", fw: "ploaie", en: "rain", pos: "n", g: "f" },
    { key: "zapada", fw: "zapada", en: "snow", pos: "n", g: "f" },
    { key: "vant", fw: "vant", en: "wind", pos: "n", g: "n" },
    { key: "furtuna", fw: "furtuna", en: "storm", pos: "n", g: "f" },
    { key: "munte", fw: "munte", en: "mountain", pos: "n", g: "m" },
    { key: "deal", fw: "deal", en: "hill", pos: "n", g: "n" },
    { key: "vale", fw: "vale", en: "valley", pos: "n", g: "f" },
    { key: "camp", fw: "camp", en: "field", pos: "n", g: "n" },
    { key: "padure", fw: "padure", en: "forest", pos: "n", g: "f" },
    { key: "copac", fw: "copac", en: "tree", pos: "n", g: "m" },
    { key: "floare", fw: "floare", en: "flower", pos: "n", g: "f" },
    { key: "iarba", fw: "iarba", en: "grass", pos: "n", g: "f" },
    { key: "frunza", fw: "frunza", en: "leaf", pos: "n", g: "f" },
    { key: "radacina", fw: "radacina", en: "root", pos: "n", g: "f" },
    { key: "lac", fw: "lac", en: "lake", pos: "n", g: "n" },
    { key: "piatra", fw: "piatra", en: "stone", pos: "n", g: "f" },
    { key: "nisip", fw: "nisip", en: "sand", pos: "n", g: "n" },
    { key: "pamant", fw: "pamant", en: "earth, ground", pos: "n", g: "n" },
    { key: "aer", fw: "aer", en: "air", pos: "n", g: "n" },
    { key: "animal", fw: "animal", en: "animal", pos: "n", g: "n" },
    { key: "caine", fw: "caine", en: "dog", pos: "n", g: "m" },
    { key: "pisica", fw: "pisica", en: "cat", pos: "n", g: "f" },
    { key: "cal", fw: "cal", en: "horse", pos: "n", g: "m" },
    { key: "vaca", fw: "vaca", en: "cow", pos: "n", g: "f" },
    { key: "porc", fw: "porc", en: "pig", pos: "n", g: "m" },
    { key: "oaie", fw: "oaie", en: "sheep", pos: "n", g: "f" },
    { key: "gaina", fw: "gaina", en: "hen", pos: "n", g: "f" },
    { key: "pasare", fw: "pasare", en: "bird", pos: "n", g: "f" },
    { key: "sarpe", fw: "sarpe", en: "snake", pos: "n", g: "m" },
    { key: "urs", fw: "urs", en: "bear", pos: "n", g: "m" },
    { key: "lup", fw: "lup", en: "wolf", pos: "n", g: "m" },
    { key: "vulpe", fw: "vulpe", en: "fox", pos: "n", g: "f" },
    { key: "soarece", fw: "soarece", en: "mouse", pos: "n", g: "m" },
    { key: "musca", fw: "musca", en: "fly", pos: "n", g: "f" },
    { key: "albina", fw: "albina", en: "bee", pos: "n", g: "f" },
    { key: "carne", fw: "carne", en: "meat", pos: "n", g: "f" },
    { key: "lapte", fw: "lapte", en: "milk", pos: "n", g: "n" },
    { key: "ou", fw: "ou", en: "egg", pos: "n", g: "n" },
    { key: "branza", fw: "branza", en: "cheese", pos: "n", g: "f" },
    { key: "unt", fw: "unt", en: "butter", pos: "n", g: "n" },
    { key: "zahar", fw: "zahar", en: "sugar", pos: "n", g: "n" },
    { key: "sare", fw: "sare", en: "salt", pos: "n", g: "f" },
    { key: "ulei", fw: "ulei", en: "oil", pos: "n", g: "n" },
    { key: "orez", fw: "orez", en: "rice", pos: "n", g: "n" },
    { key: "cartof", fw: "cartof", en: "potato", pos: "n", g: "m" },
    { key: "rosie", fw: "rosie", en: "tomato", pos: "n", g: "f" },
    { key: "mar", fw: "mar", en: "apple", pos: "n", g: "n" },
    { key: "para", fw: "para", en: "pear", pos: "n", g: "f" },
    { key: "strugure", fw: "strugure", en: "grape", pos: "n", g: "m" },
    { key: "leguma", fw: "leguma", en: "vegetable", pos: "n", g: "f" },
    { key: "fruct", fw: "fruct", en: "fruit", pos: "n", g: "n" },
    { key: "supa", fw: "supa", en: "soup", pos: "n", g: "f" },
    { key: "vin", fw: "vin", en: "wine", pos: "n", g: "n" },
    { key: "bere", fw: "bere", en: "beer", pos: "n", g: "f" },
    { key: "cafea", fw: "cafea", en: "coffee", pos: "n", g: "f" },
    { key: "ceai", fw: "ceai", en: "tea", pos: "n", g: "n" },
    { key: "mancare", fw: "mancare", en: "food", pos: "n", g: "f" },
    { key: "mic dejun", fw: "mic dejun", en: "breakfast", pos: "n", g: "n" },
    { key: "pranz", fw: "pranz", en: "lunch", pos: "n", g: "n" },
    { key: "cina", fw: "cina", en: "dinner", pos: "n", g: "f" },
    { key: "haina", fw: "haina", en: "coat", pos: "n", g: "f" },
    { key: "camasa", fw: "camasa", en: "shirt", pos: "n", g: "f" },
    { key: "pantaloni", fw: "pantaloni", en: "trousers", pos: "n", g: "m" },
    { key: "rochie", fw: "rochie", en: "dress", pos: "n", g: "f" },
    { key: "pantof", fw: "pantof", en: "shoe", pos: "n", g: "m" },
    { key: "palarie", fw: "palarie", en: "hat", pos: "n", g: "f" },
    { key: "ceas", fw: "ceas", en: "watch, clock", pos: "n", g: "n" },
    { key: "cheie", fw: "cheie", en: "key", pos: "n", g: "f" },
    { key: "hartie", fw: "hartie", en: "paper", pos: "n", g: "f" },
    { key: "creion", fw: "creion", en: "pencil", pos: "n", g: "n" },
    { key: "scrisoare", fw: "scrisoare", en: "letter", pos: "n", g: "f" },
    { key: "ziar", fw: "ziar", en: "newspaper", pos: "n", g: "n" },
    { key: "telefon", fw: "telefon", en: "telephone", pos: "n", g: "n" },
    { key: "calculator", fw: "calculator", en: "computer", pos: "n", g: "n" },
    { key: "imagine", fw: "imagine", en: "image", pos: "n", g: "f" },
    { key: "muzica", fw: "muzica", en: "music", pos: "n", g: "f" },
    { key: "cantec", fw: "cantec", en: "song", pos: "n", g: "n" },
    { key: "film", fw: "film", en: "film", pos: "n", g: "n" },
    { key: "joc", fw: "joc", en: "game", pos: "n", g: "n" },
    { key: "munca", fw: "munca", en: "work", pos: "n", g: "f" },
    { key: "treaba", fw: "treaba", en: "task, matter", pos: "n", g: "f" },
    { key: "afacere", fw: "afacere", en: "business", pos: "n", g: "f" },
    { key: "plan", fw: "plan", en: "plan", pos: "n", g: "n" },
    { key: "scop", fw: "scop", en: "purpose", pos: "n", g: "n" },
    { key: "rezultat", fw: "rezultat", en: "result", pos: "n", g: "n" },
    { key: "cauza", fw: "cauza", en: "cause", pos: "n", g: "f" },
    { key: "efect", fw: "efect", en: "effect", pos: "n", g: "n" },
    { key: "putere", fw: "putere", en: "power", pos: "n", g: "f" },
    { key: "forta", fw: "forta", en: "force", pos: "n", g: "f" },
    { key: "razboi", fw: "razboi", en: "war", pos: "n", g: "n" },
    { key: "pace", fw: "pace", en: "peace", pos: "n", g: "f" },
    { key: "lege", fw: "lege", en: "law", pos: "n", g: "f" },
    { key: "drept", fw: "drept", en: "right", pos: "n", g: "n" },
    { key: "guvern", fw: "guvern", en: "government", pos: "n", g: "n" },
    { key: "stat", fw: "stat", en: "state", pos: "n", g: "n" },
    { key: "popor", fw: "popor", en: "people, nation", pos: "n", g: "n" },
    { key: "rege", fw: "rege", en: "king", pos: "n", g: "m" },
    { key: "regina", fw: "regina", en: "queen", pos: "n", g: "f" },
    { key: "armata", fw: "armata", en: "army", pos: "n", g: "f" },
    { key: "soldat", fw: "soldat", en: "soldier", pos: "n", g: "m" },
    { key: "dusman", fw: "dusman", en: "enemy", pos: "n", g: "m" },
    { key: "victorie", fw: "victorie", en: "victory", pos: "n", g: "f" },
    { key: "infrangere", fw: "infrangere", en: "defeat", pos: "n", g: "f" },
    { key: "istorie", fw: "istorie", en: "history", pos: "n", g: "f" },
    { key: "trecut", fw: "trecut", en: "past", pos: "n", g: "n" },
    { key: "viitor", fw: "viitor", en: "future", pos: "n", g: "n" },
    { key: "prezent", fw: "prezent", en: "present", pos: "n", g: "n" },
    { key: "inceput", fw: "inceput", en: "beginning", pos: "n", g: "n" },
    { key: "sfarsit", fw: "sfarsit", en: "end", pos: "n", g: "n" },
    { key: "mijloc", fw: "mijloc", en: "middle", pos: "n", g: "n" },
    { key: "parte", fw: "parte", en: "part", pos: "n", g: "f" },
    { key: "bucata", fw: "bucata", en: "piece", pos: "n", g: "f" },
    { key: "grup", fw: "grup", en: "group", pos: "n", g: "n" },
    { key: "multime", fw: "multime", en: "crowd", pos: "n", g: "f" },
    { key: "numar", fw: "numar", en: "number", pos: "n", g: "n" },
    { key: "ordine", fw: "ordine", en: "order", pos: "n", g: "f" },
    { key: "forma", fw: "forma", en: "form, shape", pos: "n", g: "f" },
    { key: "culoare", fw: "culoare", en: "colour", pos: "n", g: "f" },
    { key: "lumina", fw: "lumina", en: "light", pos: "n", g: "f" },
    { key: "umbra", fw: "umbra", en: "shadow", pos: "n", g: "f" },
    { key: "sunet", fw: "sunet", en: "sound", pos: "n", g: "n" },
    { key: "voce", fw: "voce", en: "voice", pos: "n", g: "f" },
    { key: "miros", fw: "miros", en: "smell", pos: "n", g: "n" },
    { key: "gust", fw: "gust", en: "taste", pos: "n", g: "n" },
    { key: "durere", fw: "durere", en: "pain", pos: "n", g: "f" },
    { key: "frica", fw: "frica", en: "fear", pos: "n", g: "f" },
    { key: "bucurie", fw: "bucurie", en: "joy", pos: "n", g: "f" },
    { key: "speranta", fw: "speranta", en: "hope", pos: "n", g: "f" },
    { key: "dragoste", fw: "dragoste", en: "love", pos: "n", g: "f" },
    { key: "ura", fw: "ura", en: "hatred", pos: "n", g: "f" },
    { key: "manie", fw: "manie", en: "anger", pos: "n", g: "f" },
    { key: "rusine", fw: "rusine", en: "shame", pos: "n", g: "f" },
    { key: "curaj", fw: "curaj", en: "courage", pos: "n", g: "n" },
    { key: "slabiciune", fw: "slabiciune", en: "weakness", pos: "n", g: "f" },
    { key: "minte", fw: "minte", en: "mind", pos: "n", g: "f" },
    { key: "suflet", fw: "suflet", en: "soul", pos: "n", g: "n" },
    { key: "trup", fw: "trup", en: "body", pos: "n", g: "n" },
    { key: "sange", fw: "sange", en: "blood", pos: "n", g: "n" },
    { key: "os", fw: "os", en: "bone", pos: "n", g: "n" },
    { key: "piele", fw: "piele", en: "skin", pos: "n", g: "f" },
    { key: "par", fw: "par", en: "hair", pos: "n", g: "n" },
    { key: "dinte", fw: "dinte", en: "tooth", pos: "n", g: "m" },
    { key: "ureche", fw: "ureche", en: "ear", pos: "n", g: "f" },
    { key: "nas", fw: "nas", en: "nose", pos: "n", g: "n" },
    { key: "buza", fw: "buza", en: "lip", pos: "n", g: "f" },
    { key: "brat", fw: "brat", en: "arm", pos: "n", g: "n" },
    { key: "deget", fw: "deget", en: "finger", pos: "n", g: "n" },
    { key: "umar", fw: "umar", en: "shoulder", pos: "n", g: "m" },
    { key: "spate", fw: "spate", en: "back", pos: "n", g: "n" },
    { key: "piept", fw: "piept", en: "chest", pos: "n", g: "n" },
    { key: "burta", fw: "burta", en: "belly", pos: "n", g: "f" },
    { key: "genunchi", fw: "genunchi", en: "knee", pos: "n", g: "m" },
    { key: "a respira", fw: "a respira", en: "to breathe", pos: "v" },
    { key: "a tusi", fw: "a tusi", en: "to cough", pos: "v" },
    { key: "a atinge", fw: "a atinge", en: "to touch", pos: "v" },
    { key: "a mirosi", fw: "a mirosi", en: "to smell", pos: "v" },
    { key: "a gusta", fw: "a gusta", en: "to taste", pos: "v" },
    { key: "boala", fw: "boala", en: "illness", pos: "n", g: "f" },
    { key: "sanatate", fw: "sanatate", en: "health", pos: "n", g: "f" },
    { key: "medic", fw: "medic", en: "doctor", pos: "n", g: "m" },
    { key: "medicament", fw: "medicament", en: "medicine", pos: "n", g: "n" },
    { key: "ajutor", fw: "ajutor", en: "help", pos: "n", g: "n" },
    { key: "nevoie", fw: "nevoie", en: "need", pos: "n", g: "f" },
    { key: "dorinta", fw: "dorinta", en: "desire", pos: "n", g: "f" },
    { key: "placere", fw: "placere", en: "pleasure", pos: "n", g: "f" },
    { key: "noroc", fw: "noroc", en: "luck", pos: "n", g: "n" },
    { key: "ghinion", fw: "ghinion", en: "bad luck", pos: "n", g: "n" },
    { key: "sansa", fw: "sansa", en: "chance", pos: "n", g: "f" },
    { key: "greseala", fw: "greseala", en: "mistake", pos: "n", g: "f" },
    { key: "vina", fw: "vina", en: "fault, guilt", pos: "n", g: "f" },
    { key: "pedeapsa", fw: "pedeapsa", en: "punishment", pos: "n", g: "f" },
    { key: "rasplata", fw: "rasplata", en: "reward", pos: "n", g: "f" },
    { key: "pret", fw: "pret", en: "price", pos: "n", g: "n" },
    { key: "cost", fw: "cost", en: "cost", pos: "n", g: "n" },
    { key: "plata", fw: "plata", en: "payment", pos: "n", g: "f" },
    { key: "datorie", fw: "datorie", en: "debt, duty", pos: "n", g: "f" },
    { key: "avere", fw: "avere", en: "wealth", pos: "n", g: "f" },
    { key: "saracie", fw: "saracie", en: "poverty", pos: "n", g: "f" },
    { key: "odihna", fw: "odihna", en: "rest", pos: "n", g: "f" },
    { key: "somn", fw: "somn", en: "sleep", pos: "n", g: "n" },
    { key: "trezire", fw: "trezire", en: "awakening", pos: "n", g: "f" },
    { key: "calatorie", fw: "calatorie", en: "journey", pos: "n", g: "f" },
    { key: "bilet", fw: "bilet", en: "ticket", pos: "n", g: "n" },
    { key: "tren", fw: "tren", en: "train", pos: "n", g: "n" },
    { key: "avion", fw: "avion", en: "plane", pos: "n", g: "n" },
    { key: "vapor", fw: "vapor", en: "ship", pos: "n", g: "n" },
    { key: "barca", fw: "barca", en: "boat", pos: "n", g: "f" },
    { key: "roata", fw: "roata", en: "wheel", pos: "n", g: "f" },
    { key: "motor", fw: "motor", en: "engine", pos: "n", g: "n" },
    { key: "benzina", fw: "benzina", en: "petrol", pos: "n", g: "f" },
    { key: "viteza", fw: "viteza", en: "speed", pos: "n", g: "f" },
    { key: "distanta", fw: "distanta", en: "distance", pos: "n", g: "f" },
    { key: "directie", fw: "directie", en: "direction", pos: "n", g: "f" },
    { key: "nord", fw: "nord", en: "north", pos: "n", g: "n" },
    { key: "sud", fw: "sud", en: "south", pos: "n", g: "n" },
    { key: "est", fw: "est", en: "east", pos: "n", g: "n" },
    { key: "vest", fw: "vest", en: "west", pos: "n", g: "n" },
    { key: "stanga", fw: "stanga", en: "left", pos: "n", g: "f" },
    { key: "dreapta", fw: "dreapta", en: "right", pos: "n", g: "f" },
    { key: "colt", fw: "colt", en: "corner", pos: "n", g: "n" },
    { key: "margine", fw: "margine", en: "edge", pos: "n", g: "f" },
    { key: "centru", fw: "centru", en: "centre", pos: "n", g: "n" },
    { key: "varf", fw: "varf", en: "top, peak", pos: "n", g: "n" },
    { key: "fund", fw: "fund", en: "bottom", pos: "n", g: "n" },
    { key: "gaura", fw: "gaura", en: "hole", pos: "n", g: "f" },
    { key: "linie", fw: "linie", en: "line", pos: "n", g: "f" },
    { key: "cerc", fw: "cerc", en: "circle", pos: "n", g: "n" },
    { key: "patrat", fw: "patrat", en: "square", pos: "n", g: "n" },
    { key: "punct", fw: "punct", en: "point, dot", pos: "n", g: "n" },
    { key: "semn", fw: "semn", en: "sign", pos: "n", g: "n" },
    { key: "desen", fw: "desen", en: "drawing", pos: "n", g: "n" },
    { key: "tablou", fw: "tablou", en: "painting", pos: "n", g: "n" },
    { key: "statuie", fw: "statuie", en: "statue", pos: "n", g: "f" },
    { key: "cladire", fw: "cladire", en: "building", pos: "n", g: "f" },
    { key: "turn", fw: "turn", en: "tower", pos: "n", g: "n" },
    { key: "zid", fw: "zid", en: "wall", pos: "n", g: "n" },
    { key: "poarta", fw: "poarta", en: "gate", pos: "n", g: "f" },
    { key: "gard", fw: "gard", en: "fence", pos: "n", g: "n" },
    { key: "scara", fw: "scara", en: "stairs, ladder", pos: "n", g: "f" },
    { key: "etaj", fw: "etaj", en: "floor, storey", pos: "n", g: "n" },
    { key: "subsol", fw: "subsol", en: "basement", pos: "n", g: "n" },
    { key: "acoperamant", fw: "acoperamant", en: "cover", pos: "n", g: "n" },
    { key: "cuibul", fw: "cuibul", en: "nest", pos: "n", g: "n" },
    { key: "vizuina", fw: "vizuina", en: "den", pos: "n", g: "f" },
    { key: "a locui", fw: "a locui", en: "to dwell", pos: "v" },
    { key: "a sta", fw: "a sta", en: "to stay, sit", pos: "v" },
    { key: "a se aseza", fw: "a se aseza", en: "to sit down", pos: "v" },
    { key: "a se ridica", fw: "a se ridica", en: "to stand up", pos: "v" },
    { key: "a se intinde", fw: "a se intinde", en: "to lie down", pos: "v" },
    { key: "a se odihni", fw: "a se odihni", en: "to rest", pos: "v" },
    { key: "a se trezi", fw: "a se trezi", en: "to wake up", pos: "v" },
    { key: "a se imbraca", fw: "a se imbraca", en: "to get dressed", pos: "v" },
    { key: "a se spala", fw: "a se spala", en: "to wash up", pos: "v" },
    { key: "a se grabi", fw: "a se grabi", en: "to hurry", pos: "v" },
    { key: "a se intoarce", fw: "a se intoarce", en: "to return", pos: "v" },
    { key: "a se apropia", fw: "a se apropia", en: "to approach", pos: "v" },
    { key: "a se departa", fw: "a se departa", en: "to move away", pos: "v" },
    { key: "a se opri", fw: "a se opri", en: "to stop oneself", pos: "v" },
    { key: "a se misca", fw: "a se misca", en: "to move", pos: "v" },
    { key: "clasa", fw: "clasa", en: "class", pos: "n", g: "f" },
    { key: "elev", fw: "elev", en: "pupil", pos: "n", g: "m" },
    { key: "profesor", fw: "profesor", en: "teacher", pos: "n", g: "m" },
    { key: "student", fw: "student", en: "student", pos: "n", g: "m" },
    { key: "lectie", fw: "lectie", en: "lesson", pos: "n", g: "f" },
    { key: "examen", fw: "examen", en: "exam", pos: "n", g: "n" },
    { key: "nota", fw: "nota", en: "grade, note", pos: "n", g: "f" },
    { key: "caiet", fw: "caiet", en: "notebook", pos: "n", g: "n" },
    { key: "stilou", fw: "stilou", en: "pen", pos: "n", g: "n" },
    { key: "tabla", fw: "tabla", en: "blackboard", pos: "n", g: "f" },
    { key: "biblioteca", fw: "biblioteca", en: "library", pos: "n", g: "f" },
    { key: "universitate", fw: "universitate", en: "university", pos: "n", g: "f" },
    { key: "stiinta", fw: "stiinta", en: "science", pos: "n", g: "f" },
    { key: "arta", fw: "arta", en: "art", pos: "n", g: "f" },
    { key: "matematica", fw: "matematica", en: "maths", pos: "n", g: "f" },
    { key: "a numara", fw: "a numara", en: "to count", pos: "v" },
    { key: "a aduna", fw: "a aduna", en: "to add, gather", pos: "v" },
    { key: "a scadea", fw: "a scadea", en: "to subtract", pos: "v" },
    { key: "a inmulti", fw: "a inmulti", en: "to multiply", pos: "v" },
    { key: "a imparti", fw: "a imparti", en: "to divide", pos: "v" },
    { key: "a masura", fw: "a masura", en: "to measure", pos: "v" },
    { key: "a cantari", fw: "a cantari", en: "to weigh", pos: "v" },
    { key: "greutate", fw: "greutate", en: "weight", pos: "n", g: "f" },
    { key: "inaltime", fw: "inaltime", en: "height", pos: "n", g: "f" },
    { key: "lungime", fw: "lungime", en: "length", pos: "n", g: "f" },
    { key: "latime", fw: "latime", en: "width", pos: "n", g: "f" },
    { key: "marime", fw: "marime", en: "size", pos: "n", g: "f" },
    { key: "cantitate", fw: "cantitate", en: "quantity", pos: "n", g: "f" },
    { key: "calitate", fw: "calitate", en: "quality", pos: "n", g: "f" },
    { key: "fel", fw: "fel", en: "kind, way", pos: "n", g: "n" },
    { key: "tip", fw: "tip", en: "type", pos: "n", g: "n" },
    { key: "exemplu", fw: "exemplu", en: "example", pos: "n", g: "n" },
    { key: "model", fw: "model", en: "model", pos: "n", g: "n" },
    { key: "regula", fw: "regula", en: "rule", pos: "n", g: "f" },
    { key: "sistem", fw: "sistem", en: "system", pos: "n", g: "n" },
    { key: "metoda", fw: "metoda", en: "method", pos: "n", g: "f" },
    { key: "masura", fw: "masura", en: "measure", pos: "n", g: "f" },
    { key: "conditie", fw: "conditie", en: "condition", pos: "n", g: "f" },
    { key: "situatie", fw: "situatie", en: "situation", pos: "n", g: "f" },
    { key: "stare", fw: "stare", en: "state, condition", pos: "n", g: "f" },
    { key: "schimbare", fw: "schimbare", en: "change", pos: "n", g: "f" },
    { key: "miscare", fw: "miscare", en: "movement", pos: "n", g: "f" },
    { key: "actiune", fw: "actiune", en: "action", pos: "n", g: "f" },
    { key: "fapta", fw: "fapta", en: "deed", pos: "n", g: "f" },
    { key: "obicei", fw: "obicei", en: "habit", pos: "n", g: "n" },
    { key: "traditie", fw: "traditie", en: "tradition", pos: "n", g: "f" },
    { key: "cultura", fw: "cultura", en: "culture", pos: "n", g: "f" },
    { key: "societate", fw: "societate", en: "society", pos: "n", g: "f" },
    { key: "comunitate", fw: "comunitate", en: "community", pos: "n", g: "f" },
    { key: "familie", fw: "familie", en: "family", pos: "n", g: "f" },
    { key: "rude", fw: "rude", en: "relatives", pos: "n", g: "f" },
    { key: "vecin", fw: "vecin", en: "neighbour", pos: "n", g: "m" },
    { key: "strain", fw: "strain", en: "stranger, foreigner", pos: "n", g: "m" },
    { key: "oaspete", fw: "oaspete", en: "guest", pos: "n", g: "m" },
    { key: "gazda", fw: "gazda", en: "host", pos: "n", g: "f" },
    { key: "public", fw: "public", en: "public", pos: "n", g: "n" },
    { key: "audienta", fw: "audienta", en: "audience", pos: "n", g: "f" },
    { key: "spectator", fw: "spectator", en: "spectator", pos: "n", g: "m" },
    { key: "actor", fw: "actor", en: "actor", pos: "n", g: "m" },
    { key: "scena", fw: "scena", en: "stage, scene", pos: "n", g: "f" },
    { key: "teatru", fw: "teatru", en: "theatre", pos: "n", g: "n" },
    { key: "rol", fw: "rol", en: "role", pos: "n", g: "n" },
    { key: "personaj", fw: "personaj", en: "character", pos: "n", g: "n" },
    { key: "autor", fw: "autor", en: "author", pos: "n", g: "m" },
    { key: "scriitor", fw: "scriitor", en: "writer", pos: "n", g: "m" },
    { key: "cititor", fw: "cititor", en: "reader", pos: "n", g: "m" },
    { key: "pagina", fw: "pagina", en: "page", pos: "n", g: "f" },
    { key: "capitol", fw: "capitol", en: "chapter", pos: "n", g: "n" },
    { key: "rand", fw: "rand", en: "line, turn", pos: "n", g: "n" },
    { key: "text", fw: "text", en: "text", pos: "n", g: "n" },
    { key: "titlu", fw: "titlu", en: "title", pos: "n", g: "n" },
    { key: "subiect", fw: "subiect", en: "subject", pos: "n", g: "n" },
    { key: "tema", fw: "tema", en: "theme", pos: "n", g: "f" },
    { key: "sens", fw: "sens", en: "meaning, sense", pos: "n", g: "n" },
    { key: "inteles", fw: "inteles", en: "meaning", pos: "n", g: "n" },
    { key: "explicatie", fw: "explicatie", en: "explanation", pos: "n", g: "f" },
    { key: "descriere", fw: "descriere", en: "description", pos: "n", g: "f" },
    { key: "detaliu", fw: "detaliu", en: "detail", pos: "n", g: "n" },
    { key: "amanunt", fw: "amanunt", en: "detail", pos: "n", g: "n" },
    { key: "rezumat", fw: "rezumat", en: "summary", pos: "n", g: "n" },
    { key: "concluzie", fw: "concluzie", en: "conclusion", pos: "n", g: "f" },
    { key: "dovada", fw: "dovada", en: "proof", pos: "n", g: "f" },
    { key: "argument", fw: "argument", en: "argument", pos: "n", g: "n" },
    { key: "motiv", fw: "motiv", en: "reason, motive", pos: "n", g: "n" },
    { key: "scuza", fw: "scuza", en: "excuse", pos: "n", g: "f" },
    { key: "promisiune", fw: "promisiune", en: "promise", pos: "n", g: "f" },
    { key: "intelegere", fw: "intelegere", en: "agreement", pos: "n", g: "f" },
    { key: "acord", fw: "acord", en: "agreement", pos: "n", g: "n" },
    { key: "contract", fw: "contract", en: "contract", pos: "n", g: "n" },
    { key: "limita", fw: "limita", en: "limit", pos: "n", g: "f" },
    { key: "hotar", fw: "hotar", en: "border", pos: "n", g: "n" },
    { key: "frontiera", fw: "frontiera", en: "frontier", pos: "n", g: "f" },
    { key: "granita", fw: "granita", en: "border", pos: "n", g: "f" }
  ]
};
